input_csv: data/metadata/isic2018_raw.csv  # dane do przetworzenia
output_dir: data/processed
resize: [256, 256]
normalize: true
save_format: png
hair_removal:
  enabled: true
artifacts:
  save_examples: 10

